Proyecto1_LA/Controllers/CarritoController.cs
using Proyecto1_LA.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Proyecto1_LA.Controllers
{
    
    public class CarritoController : Controller
    {
        Boolean m;
        private Model1 db = new Model1();
        // GET: Carrito
        public ActionResult AgregarCarrito(int id) //PASAMOS EL ID DEL PRODUCTO  Y CREAMOS LA LISTA
        {
            if (Session["carrito"]==null)
            {
                List<CarritoItem> compras = new List<CarritoItem>();
                compras.Add(new CarritoItem(db.Productoes.Find(id), 1));
                Session["carrito"] = compras;
            }
            else
            {
                List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
                int IndexExistente = getIndex(id);
                if (IndexExistente == -1)//NO ESTABA EL PRODUCTO
                    compras.Add(new CarritoItem(db.Productoes.Find(id), 1));

                else
                    compras[IndexExistente].Cantidad++;
                   Session["carrito"] = compras;                 
            }

            return View();
        }
        string usuario ="";

        private int getIndex(int id)//BUSCAMOS LA POSICION Q ESTA EL ID DEL PRODUCTO SI EXISTE
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            for (int i = 0; i < compras.Count; i++)
            {
                if (compras[i].Producto.idProducto == id)
                {
                    return i;
                }
            }
            return -1;


        }
        public void validacion()
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];

            DetalleFactura nueva = new DetalleFactura();
            string socket1 = "";
            string socket2 = "";
            int count1 = 0;
            foreach (var item in Session["carrito"] as List<Proyecto1_LA.Models.CarritoItem>)
            {
                string caracter = "";
                Producto nuevopro = new Producto();
                int a = 0;
                int b = 0;
              nuevopro.Descripcion = item.Producto.Descripcion;
             char[] Cadena = nuevopro.Descripcion.ToCharArray(); //aqui se cargar 

                for (int i = 0; i < Cadena.Length; i++) //aqui se descarada la cadena 
                {
                    if (b ==1)
                    {

                    }
                    else
                    {

                    
                    if (Cadena[i] == ' ' || Cadena[i] == '\n')
                    {

                        if (a > 0)
                        {
                                if (count1 == 0)
                                {
                                    socket1 = "Socket:" + caracter;
                                    b = 1;
                                    count1 = 1;

                                }
                                else
                                {
                                    socket2 = "Socket:" + caracter;
                                    b = 1;
                                    count1 = 1;
                                }

                        }
                        if (caracter == " Socket:" || caracter == "Socket:") 
                        {
                            a = i;         
                            

                        }
                        caracter = "";

                    }
                    caracter = caracter + Cadena[i];
                    }
                }


            }
            if (socket1 == socket2)
            {
                m = true;
            }
            else
            {
                m = false;
            }
        }
        public ActionResult FinalizarCompra()
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            if (compras !=null && compras.Count>0)
            {
                validacion();
                if (m == true )
                {
                    //venta /CREAMOS LA FACTURA
                    Factura nuevafactura = new Factura();
                    nuevafactura.FechaCreado = DateTime.Now;
                    nuevafactura.Total_Venta = compras.Sum(x => x.Producto.PrecioUnitario * x.Cantidad);
                    usuario = User.Identity.Name; //UserManager
                    nuevafactura.Nombre_Usuario = usuario;

                    db.Facturas.Add(nuevafactura);
                    db.SaveChanges();
                    //factura creada
                    ///GUARDAMOS LOS DETALLES
                    DetalleFactura nueva = new DetalleFactura();

                    foreach (var item in Session["carrito"] as List<Proyecto1_LA.Models.CarritoItem>)
                    {

                        nueva.Nombre = item.Producto.Nombre;
                        nueva.PrecioVenta = item.Producto.PrecioUnitario;
                        nueva.Cantidad = item.Cantidad;
                        nueva.FechaCreado = DateTime.Now;
                        nueva.NombreUsuario = usuario;
                        nueva.idFactura = nuevafactura.idFactura;
                        db.DetalleFacturas.Add(nueva);
                        db.SaveChanges();

                        //AQUI REsTAMO LA CANTIDAD DEL PRODUCTOS
                        Producto nuevopro = new Producto();
                        //     nuevopro.Categorias = item.Producto.Categorias;
                        //   nuevopro.SubCategorias = item.Producto.SubCategorias;

                        nuevopro.Nombre = item.Producto.Nombre;
                        nuevopro.FechaCreado = item.Producto.FechaCreado;
                        nuevopro.idCategoria = item.Producto.idCategoria;
                        nuevopro.Descripcion = item.Producto.Descripcion;
                        nuevopro.PrecioUnitario = item.Producto.PrecioUnitario;
                        nuevopro.idProducto = item.Producto.idProducto;
                        nuevopro.idSubCategoria = item.Producto.idSubCategoria;
                        nuevopro.Cantidad = item.Producto.Cantidad - item.Cantidad;
                        db.Entry(nuevopro).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    compras.Clear();
                }
                else
                {
                    return View("AgregarCarrito");

                }

            }

            return View();

        }
        public ActionResult Delete(int id)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            compras.RemoveAt(getIndex(id));
            return View("AgregarCarrito");
        }


    }
}

Proyecto1_LA/Controllers/ComprarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto1_LA.Models;
using PagedList;
namespace Proyecto1_LA.Controllers
{
    public class ComprarController : Controller
    {
        private Model1 db = new Model1();
     
        // GET: Comprar
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Productoes.ToList().OrderBy(x=>x.Nombre));

        }

        //public ActionResult Busq_product_nombre(string nombre_producto)
        //{
        //    var nombrep = from s in db.Productoes select s;
        //    if (!string.IsNullOrEmpty(nombre_producto))
        //    {
        //        nombrep = nombrep.Where(j => j.Nombre.Contains(nombre_producto));
               
        //    }
        //    return View(db.Productoes);
        //}

        [HttpPost]
        public ActionResult Index(string inpBuscar, string idCategoria, double precio=0, double precio2=0)
        {
            
            if (inpBuscar.Length > 0)
            {
                var RegFiltrado = (from f in db.Productoes
                                   where f.Nombre.StartsWith(inpBuscar) orderby f.Nombre descending
                                   select f).Take(15);
            

                return View(RegFiltrado.ToList());
            }
            if (idCategoria.Length>0)
            {
                var RegFiltrado = (from f in db.Productoes
                                   where f.Categorias.Nombre.StartsWith(idCategoria)
                                   orderby f.Nombre descending
                                   select f).Take(15);


                return View(RegFiltrado.ToList());
            }

//            SELECT idProducto, Nombre, Descripcion, PrecioUnitario, Cantidad, idCategoria, idSubCategoria, FechaCreado
//FROM dbo.Productoes
//WHERE(PrecioUnitario > @precio2) AND(PrecioUnitario < @precio3)
                if (precio>0 && precio2>0)
            {
                var RegFiltrado = (from f in db.Productoes
                                   where(f.PrecioUnitario > @precio) where(f.PrecioUnitario< @precio2)
             
                                   orderby f.Nombre descending
                                   select f).Take(15);


                return View(RegFiltrado.ToList());
            }
            else
            {
                return View(db.Productoes.OrderByDescending(f =>
                f.Nombre).Take(20).ToList());
            }

        }

    }
}

Proyecto1_LA/Views/Comprar/Index.cshtml
@model IEnumerable<Proyecto1_LA.Models.Producto>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Productos</h2>

@*@using (Html.BeginForm())
{
    <fieldset>
        <legend>Criterios de búsqueda</legend>
        <div class="form-horizontal">
            <div class="form-group">
                <label class="control-label col-md-2">Buscar:</label>
                <div class="col-md-10">
                    <input type="text" name="inpBuscar" class="form-control"
                           placeholder="Introduzca el texto de búsqueda" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <i class="fa fa-refresh" style="color:blue;"></i>
                    <input type="submit" value="Filtrar" class="btn btn-default" id="btngetdata">
                </div>
            </div>
        </div>
        </fieldset>
        }*@


@using (Html.BeginForm())
{
    <fieldset>
        <legend>Criterios de búsqueda</legend>
        @Html.Label("Buscar", "Nombre Producto:")
        @Html.TextBox("inpBuscar")
        @Html.Label("categorías:")
        @Html.TextBox("idCategoria")
        @Html.Label("rango de precio:")
        @Html.TextBox("precio")
        @Html.TextBox("precio2")

        <input type="submit" value="Filtrar" class="btn btn-default" id="btngetdata">
    </fieldset><br />
}



        <p>
            Selecciones Agregar Al Carrito
        </p>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PrecioUnitario)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cantidad)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Categorias.Nombre)
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PrecioUnitario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cantidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Categorias.Nombre)
                    </td>
                    <td>
                        @Html.ActionLink("Agregar al Carrito", "AgregarCarrito", "Carrito", new { id = item.idProducto }, null)
                       
                    </td>
                </tr>
            }

        </table>
        @*@Scripts.Render("~/bundles/jqueryval")*@